### ISSUE TITLE
change "enrol me in this course" to "add this course to the coursecollection block"

### ISSUE THREAD

**Issue by danmarsden** [DrCuriosity/moodle-block_coursecollection#2]
https://github.com/DrCuriosity/moodle-block_coursecollection/blob/master/block_coursecollection.php#L142

I think I must have explained this badly - this should implement the method to add new courses to the course collection block - rather than allow the user to enrol. Sorry!

**Comment by DrCuriosity** [comment]
Changed to an "Add this course" link at the bottom of the Course Collection block.
